name : ci pipeline basic
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : checkout code
        uses: actions/checkout@v2
      - name: kiem tra phien ban
        run: |
          echo "Checking version..."
      - name: test
        run: |
          echo "Running tests..."

